### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by unvalley** [unvalley/rebuttal#2]
---
- [ ] `/workers`
	- [x] `/documents/[id]` : ドキュメント詳細
		- [x] マイクロタスク結果の集約ロジック 
			- [x] 意見と事実のハイライト表示ロジック
			- [x] 「事実のリソース確認」の反映
			- [x] 「意見に妥当な事実が書かれているか確認」の反映
		- [x] タスク実施状況の確認（Optional）
		- [x] ドキュメント情報の表示（Optional）
			- センテンス数や意見と事実の比率などはすぐに出せそう
	- [ ] `/tasks`: タスク詳細（タスク実施ページ）
		- [x] アサインロジックの実装
			- [x] アサインのアルゴリズムの検討
				- あるワーカーは5回同じタスクをやるべきか？それとも異なるもの？ 
			- [x] 5個アサインしたタスクが完了された後の対応
			- [x] 新規アサイン
		- [ ] タスク実施履歴（Optional）
		- [x] タスク完了
			- [x] 意見と事実の切り分け：タスク完了をセンテンスに反映する
			- [x] 事実のリソース確認
			- [x] 意見に妥当な事実が書かれているか確認
		- [ ] 機械学習による支援
			- [ ] 支援内容の検討 
- [x] `/writers`
	- [x] `/documents[id]`: ドキュメント詳細
	- [x] `/tasks`: タスク詳細
- [x] `/auth`
	- [x] /auth/signin：サインイン
	- [x] /auth/signup：サインアップ

**Comment by unvalley** [comment]
## タスク詳細ページ
![Screen Shot 2022-11-09 at 1 31 26](https://user-images.githubusercontent.com/38400669/200621807-7f819de6-cc45-4c86-af0c-31d9768624a3.png)


## ドキュメント詳細ページ
![Screen Shot 2022-11-09 at 1 33 32](https://user-images.githubusercontent.com/38400669/200622246-bcad6041-699c-4bf1-9539-9d000c181e09.png)

執筆者には右側のタスク一覧は見せなくても良い

**Comment by unvalley** [comment]
2022-1109
- [x] `Microtask`と`Paragraph`にリレーションが必要
	- [x] A `Paragraph` has `Sentences`
- [x] タスク結果をまとめるテーブルが必要
- [x] ワーカーのタスク種類は，ワーカーによって固定する
- [x]  アサインロジックは，最初に意見と事実の切り分けをすべてアサインする
	- [x] それが完了したらリソースチェックなどのタスクを振る
	- ただしこれだと切り分けタスクをすべてアサインしたあとにワーカーが完了しなければ，新しいタスクを触れなくなってしまうので検討が必要


---

- ライターの執筆方法は実験のためには，固定させても良いかもしれない 
-  評価は一旦後回し

**Comment by unvalley** [comment]
- [x] ユーザー登録
- [x] リソースタスクの実施
- [x] 意見妥当性タスクの実施
---
- [x] テキストデータからマイクロタスク生成までのロジック（画面にするか）
- [x] デプロイ
- [x] フィードバックUIの実装
- [x] タスク集約ロジック（多数決）の実装

**Comment by unvalley** [comment]
![prisma-erd](https://user-images.githubusercontent.com/38400669/202912719-d003452b-0e10-42d0-91fa-f5682806ec8a.svg)

**Comment by unvalley** [comment]
I don't need to create microtasks connected with sentences. Because, the things I need is just the results.
So, microtask-set (1/2/3) related to the results (1/2/3). Only the results (1) needs to have more results than the (2) and (3).

**Comment by unvalley** [comment]
updated schema (only `microtasks` and `microtask_results`)  is here.

```ts
model Microtask {
  id               Int               @id @default(autoincrement())
  title            String
  body             String
  kind             MicrotaskKinds
  paragraph        Paragraph         @relation(fields: [paragraphId], references: [id])
  paragraphId      Int
  sentence         Sentence          @relation(fields: [sentenceId], references: [id])
  sentenceId       Int
  microtaskResults MicrotaskResult[]

  created_at DateTime @default(now())
  updated_at DateTime @default(now()) @updatedAt

  @@map("microtasks")
}
enum Executor {
  WORKER
  SYSTEM
}

model MicrotaskResult {
  id          Int       @id @default(autoincrement())
  // MTask1: OPINION or FACT
  // MTask2/3: TRUE or FALSE (as string)
  value       String
  reason      String?
  executor    Executor  @default(WORKER)
  microtask   Microtask @relation(fields: [microtaskId], references: [id])
  microtaskId Int       @unique
  assignee      User             @relation(fields: [assigneeId], references: [id])
  assigneeId    Int
  created_at  DateTime  @default(now())
  updated_at  DateTime  @default(now()) @updatedAt
  @@map("microtask_results")
}

```

**Comment by unvalley** [comment]
## 簡易デモ後

すべてタスク実施画面について

- [ ] 文献チェックタスクの選択肢拡張
	- 文献情報が付与されているけど、妥当ではない文献情報が参照されている場合の対応
	- 現状では「ある」「ない」の2択なので対応が必要
- [x] 「回答して次のタスクへ」が反応しない
	- [x] 回答を送信しましたアラート不要では
- [x] 現状のタスク進捗を知りたい
- [x] 簡単ラベルを消す？
- [x] 戻るボタン
	- [x] 正直面倒なので無しにしたい
- [x] 意見と事実の文言とラジオボタンの距離修正
	- [x] 	ラジオボタンの選択を左に
- [x] 文献情報・事実有無
	- [x] ラジオボタン未選択&&理由未記入→「必須項目が入力されていません」アラート2回
	- [x] ラジオボタン未選択&&理由記入→「必須項目が入力されていません」アラート2回
	- [x] ラジオボタン選択&&理由未記入→次の画面に進む
- [x] タスクが終わらない問題の原因調査とfix
- [x] 意見文→妥当性、事実文→リソースチェック　になるように更新
- [ ]  wizardの状態管理の見直し
	- [x] ヘルプに行ったあと
	- [x] リロード対応
	- [ ] タブ閉じたとき対応


---

- UI系は後回しでOKなので、ロジックのバグがないようにする
- デバッグ用に「これまで実施したタスク」を表示するようにするかー
